In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
x = np.random.randint(100, 999, size=3)
print(x)

y = np.random.randint(100, 999, size=3)
print(y)

[254 591 629]
[418 347 596]


In [6]:
# 이항 유니버설 함수
np.minimum(x, y)

array([254, 347, 596])

In [8]:
x = np.array([1, 2, 5, 7, 3, 4, 6, 3])
x

array([1, 2, 5, 7, 3, 4, 6, 3])

In [10]:
x.max()

7

In [12]:
x.min()

1

In [13]:
x.sum()

31

In [15]:
x.argmax()

3

In [17]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [24]:
# 1인 경우 행별로 정렬
b = np.sort(a, axis=1)
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [43]:
# 행 간에 열을 기준으로 오름차순
b = np.sort(a, axis=0)
b

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

### seed를 활용하는 기술

난수 발생의 기준점 설정 하는 방법

필요성: 향후 ML/DL의 모델 개발시에 정확한 예측에 가까운 패터을 도출하기 위해서 수많은 다양한 경우의 수로 학습, 
    학습시에 다양한 수치값으로 학습(개발자가 직접 선별해서 입력을 어렵기 때문에 난수 로직 활용)
    
난수: 정해진 범위내의 알 수 없는 숫자를 의미

In [45]:
np.random.rand(5)

array([0.80711331, 0.63727475, 0.28554293, 0.05725381, 0.94050104])

In [46]:
np.random.seed(42)

In [47]:
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])