# NumPy 학습

- 파이썬에서 배열을 사용하기 위한 수치 해석용 표준 패키지
- 적은 메모리로 데이터를 빠르게 처리할 수 있음
- 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용
- 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠름
- 벡터화 연산(vectorized operation)을 이용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있음
- 배열 인덱싱(array indexing)을 사용한 질의(Query) 기능을 이용하여 간단한 코드로도 복잡한 수식을 계산할 수 있음
- C언어의 배열처럼 연속적인 메모리 배치를 하기 때문에 모든 원소가 같은 자료형이어야 함
- 이러한 제약사항이 있는 대신 원소에 대한 접근과 반복문 실행이 빨라짐
- ndarray 는 N-dimensional Array의 약자로 1차원, 2차원,  3차원 배열 등의 다차원 배열 자료 구조를 지원
- **2차원 배열은 행렬(matrix)** 이라고 하는데 행렬에서는 가로줄을 행 *(row)*이라고 하고 세로줄을 *열(column)*이라 함
- 다차원 배열 : 리스트의 리스트(list of list)를 이용하면 2차원 배열을 생성할 수 있음. 
- 안쪽 리스트의 길이는 행렬의 열의 수 즉, 가로 크기가 되고 바깥쪽 리스트의 길이는 행렬의 행의 수, 즉 세로 크기를 의미
- url<br>
http://www.numpy.org/<br>
https://numpy.org/doc/stable/reference/index.html


<img src='imgs/numpy.jpg' width="50%" />

### NumPy 패키지 import

> NumPy는 np라는 이름으로 임포트하는 것이 관례

In [1]:
!pip show numpy

Name: numpy
Version: 1.19.2
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\users\playdata\anaconda3\lib\site-packages
Requires: 
Required-by: tifffile, tables, statsmodels, seaborn, scipy, scikit-learn, scikit-image, PyWavelets, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, missingno, matplotlib, imageio, h5py, Bottleneck, bokeh, bkcharts, astropy


In [2]:
!pip show pandas

Name: pandas
Version: 1.1.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: c:\users\playdata\anaconda3\lib\site-packages
Requires: python-dateutil, numpy, pytz
Required-by: statsmodels, seaborn


In [3]:
import numpy as np

import time

### Numpy 필요성 인지를 위한 간략 코드
> 반복문 실행 시간 비교하기

In [4]:
#numpy 데이터 구성
start_time = time.time()

numpyArray = np.arange(10000000)

end_time = time.time() 
elapsed_time = end_time - start_time

print('Numpy 소요 시간 : ', elapsed_time)

Numpy 소요 시간 :  0.03400111198425293


In [5]:
#순수 python list

start_time = time.time()

plist = list( range(10000000) )

end_time = time.time() 
elapsed_time = end_time - start_time

print('순수 Python 소요 시간 : ', elapsed_time)


순수 Python 소요 시간 :  0.24043726921081543


In [6]:
print(numpyArray)

[      0       1       2 ... 9999997 9999998 9999999]


In [7]:
print(plist)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [8]:
type(numpyArray)

numpy.ndarray

In [9]:
type(plist)

list

In [10]:
# ms : 밀리초 (millisecond, ms)는 천 분의 1초를 가리키는 말
# s : 초
%time for _ in range(10): numpyArray = numpyArray * 2
    
%time for _ in range(10): plist = [x * 2 for x in plist]

Wall time: 532 ms
Wall time: 16.8 s


### NumPy 모듈을 사용한 1차원 배열 만들기

- array 함수에 리스트를 넣으면 배열로 변환

In [11]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(data)
type(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [12]:
# 정수 배열 -  numpy 배열 생성 문법
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(data)
type(data)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

### ndarray의 데이터 타입
-  list를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 자동 형변환을 일괄 적용

In [13]:
list = [1, 2, 'string']

nparray = np.array(list)
print(list, nparray )

[1, 2, 'string'] ['1' '2' 'string']


In [14]:
# 각 요소별 type 확인
print(type(list[0]), type(list[1]), type(list[2]))

print(type(nparray[0]), type(nparray[1]), type(nparray[2]))

<class 'int'> <class 'int'> <class 'str'>
<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>


- ndarray 내 데이터값의 타입 변경 : astype()
- 데이터 타입을 변경하는 경우는 대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용되지만, 메모리를 더 절약해야 할 경우 주로 이용
    <br>: 가령 int 형으로 충분한 경우 float 타입의 데이터를 int 형으로 변경 권장

In [15]:
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(data)
type(data[0])   # 0번째 요소의 데이터 타입 확인 

[0 1 2 3 4 5 6 7 8 9]


numpy.int32

In [16]:
# ndarray 생성시 float64로 생성
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='float')
print(data)
type(data[0])  # 0번째 요소의 데이터 타입 확인 

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


numpy.float64

In [17]:
# 이미 구성된 ndarray의 타입을 변경 해 보기 
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(data)
print(type(data[0]) )
data = data.astype('float')  # float 타입으로 변환된 복제본 생성 따라서 원본게 재대입 
print(type(data[0]))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.int32'>
<class 'numpy.float64'>


In [18]:
data.shape   

(10,)

In [19]:
data.ndim

1

### NumPy 모듈을 사용한  2차원 배열 만들기

In [20]:
data = np.array([ [1, 2, 3] ,  [4, 5, 6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
print(data.shape, data.ndim)

(2, 3) 2


In [22]:
data[0]  # 첫번째 row

array([1, 2, 3])

In [23]:
data[1]

array([4, 5, 6])

In [24]:
data[0][0] # 첫번째 row의 첫번째 column

1

In [25]:
len(data)  # 행 개수 

2

In [26]:
len(data[0])  # 0번째 row에 포함된 column 수

3

In [27]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# 5값을 55로 변경하기 힌트 : = 연산자 활용해서 변경 가능
print(data[1][1])
data[1][1] = 55
print(data)

5
[[ 1  2  3]
 [ 4 55  6]]


### NumPy 모듈을 사용한  3차원 배열 만들기

리스트의 리스트의 리스트를 이용하면 3차원 배열도 생성할 수 있음<br>
크기를 나타낼 때는 가장 **바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로** 표시<br>
예를 들어 2 x 3 x 4 배열은 다음과 같이 구성


<img src='imgs/ndim_1.jpg' width=30%>
<img src='imgs/ndim_2.jpg' width=30%><img src='imgs/ndim_3.jpg' width=50%>


> 차원과 shape 확인 후에 구조 이해하고 원하는 데이터 착출하는 연습하기

In [29]:
# 1 x 2x3x4
data = np.array([ [[1,2,3,4],[5,6,7,8],[9,10,11,12]], [[21,22,23,24], [25,26,27,28], [29,30,31,32]] ])

In [30]:
data

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [31]:
data1 = np.array([ [ [1, 11] , [2, 22] ] , [ [3, 33] , [4, 44] ] ])
print(data1)
print('-' *20)

print(data1.shape, data1.ndim)

print('-' *20)
print(data1[0])
print(data1[0][1])

[[[ 1 11]
  [ 2 22]]

 [[ 3 33]
  [ 4 44]]]
--------------------
(2, 2, 2) 3
--------------------
[[ 1 11]
 [ 2 22]]
[ 2 22]


In [32]:
data1 = np.array([ [ [1, 11] , [2, 22] ] , [ [3, 33] , [4, 44] ] ])
print(data1[0])
print(data1[0][0])
print(data1[0][0][0])
print(data1[0][0][1])

[[ 1 11]
 [ 2 22]]
[ 1 11]
1
11


In [33]:
data1 = np.array([ [ [1, 11] , [2, 22] ] , [ [3, 33] , [4, 44] ] ])
print(data1)  # 3차원 tensor
print(data1[1])  # 2차원  metrix
print(data1[1][1])  # 1차원  벡터
print(data1[1][1][0])  # scalar

[[[ 1 11]
  [ 2 22]]

 [[ 3 33]
  [ 4 44]]]
[[ 3 33]
 [ 4 44]]
[ 4 44]
4


In [34]:
# 4값을 400으로 변경
data1 = np.array([ [ [1, 11] , [2, 22] ] , [ [3, 33] , [4, 44] ] ])
data1[1][1][0] = 400
data1

array([[[  1,  11],
        [  2,  22]],

       [[  3,  33],
        [400,  44]]])

In [35]:
data1[1][0][0]

3

In [36]:
print(data.shape,  data.ndim)

(2, 3, 4) 3


In [37]:
print(data[0])
print(data[0].shape, data[0].ndim) # (3, 4) 2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4) 2


In [38]:
print(data[0][0])
print(data[0][0].shape, data[0][0].ndim)

[1 2 3 4]
(4,) 1


In [39]:
print(data[0][0][0])
print(data[0][0][0].shape, data[0][0][0].ndim)

1
() 0


In [40]:
data

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [41]:
print(data[0][0][0], data[0][2][0])

1 9


In [42]:
data1 = np.array([ [ [1] ] , [ [2] ] ])
print(data1[0][0][0]) #1

# 행, 열, 깊이 개수 확인
print(len(data1), len(data1[0]), len(data1[0][0]))

1
2 1 1


In [43]:
print(data1.shape, data1.ndim)

(2, 1, 1) 3


### <font color='red'> ndarray의 차원과 크기를 변경 : reshape() </font>

- x, y에 해당하는 parameter로 설정
- -1을 parameter로 반영할 경우 다른 parameter를 기준으로 행과 열을 자동으로 변경 및 적용해줌

In [44]:
a1 = np.arange(1, 11)
print(a1)
print(type(a1))
print(a1.ndim)
print(a1.shape)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
1
(10,)


In [45]:
# 5열로 구성
a2 = a1.reshape(-1 , 5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
# 5행으로 구성
a3 = a1.reshape(5, -1)
a3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [47]:
a3[1]

array([3, 4])

### NumPy 함수를 사용하여 배열 생성하기

- 규모가 큰 배열의 경우에는 NumPy에 내장된 루틴을 사용해서 처음부터 배열을 생성하는 것이 효율적


**주요 함수**
- zeros : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 ndarray 반환<br>
- ones <br>
- zeros_like, ones_like : api 보시고 예제 구성 직접 하기<br>
- empty<br>
- arange : 특정한 규칙에 따라 증가하는 수열 만들기<br>
- linspace, logspace : 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할<br>
- rand, randn<br>

In [48]:
# 0값으로 채워진 1차원 numpy 배열 생성
data = np.zeros(10, dtype=int)
print(data)
print(type(data))

[0 0 0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>


In [49]:
data = np.zeros(10)
data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
# 2차원 배열 생성 
data = np.zeros((2, 3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
# data 의 마지막 요소에 100으로 변경
data[1][2] = 100
data

array([[  0.,   0.,   0.],
       [  0.,   0., 100.]])

In [52]:
# 선택한 데이터르 행렬(배열) 생성
data = np.full( (3, 5), 5)
data

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [53]:
data = np.ones( (2, 3) )
data

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
# 0~10까지 2씩 증가하면서 1차원 배열
data = np.arange(0, 10, 2)
data

array([0, 2, 4, 6, 8])

In [55]:
np.linspace(0, 5, 2)

array([0., 5.])

In [56]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [57]:
# 0.1~ 1까지

np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [58]:
# 단위 행렬 도출하는 함수 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## NumPy 배열의 기초

### 배열 속성 지정

**각 배열이 보유하고 있는 속성들**


- ndim : 차원의 개수
- shape : 각 차원의 크기
- size : 전체 배열 크기


- randint(maxno, size=(nxm)) or  randint(minno, maxno, (nxm))<br>
- 정수형의 난수 발생 함수

In [59]:
# 동일한 난수 발생 함수 단, parameter 설정에 따른 차원이 다른 ndarray 생성하기
x1 = np.random.randint(10, size=6)   # 1차원 배열
print(x1)

x1 = np.random.randint(10, size=(3, 4))  # 3 x 4 2차원 배열
print(x1)

x1 = np.random.randint(10, size=(3, 4, 5)) # 3 x 4 x 5 3차원 배열 
print(x1)

[9 2 0 0 5 7]
[[3 1 2 2]
 [4 0 9 1]
 [1 1 3 7]]
[[[7 1 4 9 6]
  [5 7 9 2 8]
  [0 6 3 2 1]
  [3 8 8 9 7]]

 [[4 7 3 1 4]
  [0 3 3 5 4]
  [7 4 1 6 5]
  [8 3 6 0 3]]

 [[5 4 2 9 8]
  [8 7 2 2 0]
  [3 2 0 9 9]
  [7 4 6 0 0]]]


### 배열의 색인과  슬라이싱 
> x[start : stop : step] <br>
하위 배열에 접근하기

In [60]:
x1 = np.random.randint(10, size=6)   # 1차원 배열
print(x1)
x2 = np.arange(10)
print(x2)

[6 8 8 9 5 8]
[0 1 2 3 4 5 6 7 8 9]


In [61]:
x2[:5]

array([0, 1, 2, 3, 4])

In [62]:
x2[5:]

array([5, 6, 7, 8, 9])

In [63]:
x2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
print(x2[1:2:2])  

[1]


In [65]:
x2[2:2:2]  # 논리적인 오류 

array([], dtype=int32)

In [66]:
print(x2[1:6:2])
print(x2[1::2])

[1 3 5]
[1 3 5 7 9]


In [67]:
x2[::3]  # 3칸씩 점프하는 구성

array([0, 3, 6, 9])

In [68]:
x1

array([6, 8, 8, 9, 5, 8])

In [69]:
# -1은 마지막 데이터 요소 의미, :: 점프 의미 
x1[::-1]

array([8, 5, 9, 8, 8, 6])

In [70]:
x1

array([6, 8, 8, 9, 5, 8])

In [71]:
# 5번째 index 위치부터 뒤로 두칸씩 점프해서 데이터 slicing 
x1[5 :: -2]

array([8, 9, 8])

In [72]:
x2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
x2[5 :: -2]

array([5, 3, 1])

### 팬시 indexing
> 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당 ndarray를 반환하는 방식

In [74]:
x = np.arange(start=1, stop=10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [75]:
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [76]:
x = x.reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
y = x[ [0, 1] , 2]
y

array([3, 6])

In [78]:
y = x[ [1, 2] , 1:3]
y

array([[5, 6],
       [8, 9]])

In [79]:
x[0, 0]

1

In [80]:
x[1]

array([4, 5, 6])

### 데이터 복사 이해하기

> NumPy는 대용량 데이터 처리를 염두해 두고 설계되었기 때문에 NumPy가 데이터 복사를 남발할 경우 성능과 메모리 문제 발생 가능성이 있음
<br>
별도의 복사된 데이터를 활용하고자 할 경우 copy() 함수 사용

copy() 함수를 사용하지 않은 경우

In [81]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
x[5]

5

In [83]:
x[3:8]

array([3, 4, 5, 6, 7])

In [84]:
x[3:8] = 100 # 원본 데이터까지 수정
x

array([  0,   1,   2, 100, 100, 100, 100, 100,   8,   9])

원본 데이터를 기반으로 작업 단, 원본 데이터는 보존해야 한다면...??? 해결책

copy() 함수를 사용한 경우

In [85]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
y = x[5:8].copy()
y

array([5, 6, 7])

In [87]:
y[0] = 100
y

array([100,   6,   7])

In [88]:
x   # 원본 유지

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> 다차원 하위 배열

**reshape() : 배열의 재 구조화**

- 매우 중요
- ndarray를 특정 차원 및 크기로 변환
- 변환을 원하는 크기를 함수 인자로 부여
- 실전에서 더욱 효율적으로 사용하는 경우 인자로 -1 적용, -1을 적용할 경우에는 ndarray와 호환되는 새로운 shape로 변환해 줌

**배열 연결 및 분할**

- 여러 배열을 하나의 배열화(결합), 또는 하나의 배열을 여러 배열로 분할
- np.concatenate(numpy 배열과 python list 결합도 가능)
- np.vstack/np.hstack
- np.split/np.vsplit/np.hsplit

In [89]:
# 1차원 배열간의 결합
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

np.concatenate([x, y])  # 1차원 배열들을 1차원으로 결합 

array([1, 2, 3, 4, 5, 6])

In [90]:
z = [7, 8, 9]  # python의 순수 list

In [91]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
data = np.array([x, y])   # 1차원 ndarray들로 2차원 배열 생성 
print(type(data))
print(data.shape, data.ndim)
print(data)

<class 'numpy.ndarray'>
(2, 3) 2
[[1 2 3]
 [4 5 6]]


In [93]:
data1 = np.concatenate([x, y, z])
data2 = np.array([data1, data1])
data2

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [94]:
print(x)
print(y)
print(z)

[1 2 3]
[4 5 6]
[7, 8, 9]


In [95]:
data1 = np.concatenate([x, y, z])
data1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
data1 = np.concatenate([x, y, z], axis=0)
data1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
data1 = np.concatenate([x, y, z], axis=1)
data1

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
data1 = np.concatenate([x, y], axis=1)
data1

In [ ]:
data1 = np.concatenate([x, y])
data1

In [ ]:
x = np.array([1,2,3])     # 1차원
data = np.array([[5,6,7], [8,9,10]])   # 2차원

print(type(x), x.shape, x.ndim, data.shape, data.ndim)

print("-"*10)
print(x)

print("-"*20)
print(data)

In [ ]:
np.vstack([data, x])  # 수직으로 데이터 결합 가능

In [ ]:
np.hstack([data, x])  # data는 2행, x는 1차원으로 3개의 데이터(2행에 3개의 데이터 붙이려 하니 구조상 불가 따라서 에러 )

In [ ]:
data1 = np.concatenate([x, data], axis=1)
data1

In [ ]:
data1 = np.concatenate([x, data], axis=0)
data1

In [ ]:
data

In [ ]:
x

In [ ]:
np.vstack([data, x])

In [ ]:
np.hstack([data, x])

분할

In [ ]:
x = [1, 2, 3, 100, 100, 3, 2, 1]

In [ ]:
# unboxing
# java에선 객체 타입이 기본 타입의 변수에 대입 int i = new Integer(10); (new Integer(10)).intValue()

# python에선 다수의 데이터 덩어리가 분할되어 여러개의 변수에 대입되는 구조를 unboxing
x1, x2, x3 = np.split(x, [3, 5])
print(x1)
print(x2)
print(x3)

In [ ]:
data = np.arange(16).reshape(4, 4)
data

In [ ]:
data[0]

In [ ]:
# 0, 4, 8, 12
print(data[0][0] , data[1][0], data[2][0], data[3][0])

In [ ]:
# 가시적인 상식선(excel 구조로 간주)에선 hsplit이 row를 분할할듯 하나 내부적으로 columns 을 분할
# dim은 row 변경없이 coloum이 분할된 결과 도출

up, down = np.hsplit(data, [1])
print(up)
print(down)
print(data.shape, data.ndim, '/', up.shape, up.ndim, '/', down.shape, down.ndim)   # (4, 4) 2 / (4, 1) 2 / (4, 3) 2

In [ ]:
data

In [ ]:
up, down = np.vsplit(data, [1])
print(up)
print(down)
print(data.shape, data.ndim, '/', up.shape, up.ndim, '/', down.shape, down.ndim)  # (4, 4) 2 / (1, 4) 2 / (3, 4) 2

**혼합된 차원의 배열**

- 행의 수나 열의 수가 같은 두개 이상의 배열을 연결하여 더 큰 배열 생성하는  명령어
- np.vstack : 수직 스택, vertical stack, 컬럼 개수는 맞아야 함 <br>
- np.hstack : 수평 스택, horizontal stack, 하나의 컬럼에 속해있는 row 개수는 동일해야 함<br>
- dstack : 제 3의 축, 즉 행이나 열이 아닌 깊이 방향으로 배열을 결합, 가장 안쪽의 원소 차원이 증가
- stack : 사용자가 지정한 차원(축)으로 연결
- r_ : hstack과 함께 배열을 좌우로 연결
- c_ : 배열의 차원을 증가시킨 후 좌우로 연결, 가령 1차원 배열을 연결하면 2차원 배열이 됨
- tile : 동일한 배열을 반복하여 연결

> <font color='red'>전치 연산</font>
- 2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 작업
- 이는 배열의 T 속성으로 구할 수 있음
- 메서드가 아닌 속성

In [ ]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data

In [ ]:
data.ndim, data.shape

In [ ]:
data2 = data.T

In [ ]:
data2

In [ ]:
data2.ndim, data2.shape

In [ ]:
data = np.arange(1, 10, 1)
data

In [ ]:
data = data.reshape(3, 3)

In [ ]:
data.ndim

In [ ]:
# 중요 : CNN 시에 활용 예정 
data.flatten()

### 벡터화 연산(vectorized operation)

1.  배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리
- 일반 for 반복문 없이 한번의 연산으로 처리 가능
- 실행 속도도 빠름
- 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

<!--NAVIGATION-->
<[step02 NumPy 함수 학습](step02_NumpyFun.ipynb) >