# pandas 학습

1. 데이터 분석을 위한 모듈
2. excel과 가장 큰 차이점 : pandas는 대용량 데이터 처리가 가능
3. 데이터 분석 및 데이터 가공에 절대적으로 사용되는 library
4. 주요 학습 내용
    1. DataFrame - excel의 다수의 컬럼들을 보유한 table과 동급
    2.series - DataFrame을 구성하는 column간주

In [15]:
import pandas as pd
import numpy as np

In [7]:
pd.__version__

'1.1.3'

In [11]:
s = pd.Series([1, 2, 3])
print(s)
print(type(s))

0    1
1    2
2    3
dtype: int64
<class 'pandas.core.series.Series'>


In [16]:
print(s.values) # series 데이터들만
print(s.index) # series의 index 정보 확인
print(s.value_counts)

[1 2 3]
RangeIndex(start=0, stop=3, step=1)
<bound method IndexOpsMixin.value_counts of 0    1
1    2
2    3
dtype: int64>


In [19]:
s = pd.Series([3, 1, 2, 3, 4, np.nan])
print(s)
s.value_counts(normalize = True)

0    3.0
1    1.0
2    2.0
3    3.0
4    4.0
5    NaN
dtype: float64


3.0    0.4
4.0    0.2
2.0    0.2
1.0    0.2
dtype: float64

In [21]:
s = pd.Series(['a', 'b', 'a', np.nan])
s.value_counts()

a    2
b    1
dtype: int64

In [23]:
#
s = pd.Series(['a', 'b', 'a', np.nan])
s.value_counts(dropna=False)

a      2
b      1
NaN    1
dtype: int64

In [26]:
s = pd.Series([1, 2])
print(s)

0    1
1    2
dtype: int64


In [27]:
s = pd.Series([1.3, 2.5])
print(s)

0    1.3
1    2.5
dtype: float64


In [29]:
s = pd.Series(['a', 'b'])
print(s)

0    a
1    b
dtype: object


In [32]:
s = pd.Series([1, 2], dtype=float)
print(s)

0    1.0
1    2.0
dtype: float64


In [34]:
s = pd.Series(['a', 'b', np.nan])
print(s)
print(s.dropna())

0      a
1      b
2    NaN
dtype: object
0    a
1    b
dtype: object


In [45]:
datas = pd.date_range('20210310', periods=12)
print(datas)

DatetimeIndex(['2021-03-10', '2021-03-11', '2021-03-12', '2021-03-13',
               '2021-03-14', '2021-03-15', '2021-03-16', '2021-03-17',
               '2021-03-18', '2021-03-19', '2021-03-20', '2021-03-21'],
              dtype='datetime64[ns]', freq='D')


In [37]:
np.random.randint(10)

3

In [38]:
np.random.rand()

0.6840983994857718

In [40]:
df = pd.DataFrame(np.random.rand(5, 4))
df

0         1         2         3
0  0.104574  0.480314  0.688849  0.836123
1  0.828450  0.943234  0.064538  0.583150
2  0.069231  0.841320  0.681273  0.646317
3  0.883440  0.554777  0.071526  0.061547
4  0.205539  0.778254  0.189791  0.463278

In [48]:
df = pd.DataFrame(np.random.rand(12, 4), index=datas, columns=['a', 'b', 'c', 'd'])
df

a         b         c         d
2021-03-10  0.507056  0.792468  0.868560  0.833076
2021-03-11  0.202249  0.224287  0.513411  0.882459
2021-03-12  0.141800  0.009611  0.416795  0.252268
2021-03-13  0.481157  0.837108  0.217090  0.168004
2021-03-14  0.993059  0.697006  0.342454  0.496581
2021-03-15  0.398121  0.791812  0.110484  0.150032
2021-03-16  0.054605  0.405857  0.814229  0.790193
2021-03-17  0.008824  0.980989  0.566913  0.071107
2021-03-18  0.345077  0.074415  0.609670  0.229281
2021-03-19  0.585383  0.798180  0.247769  0.236698
2021-03-20  0.172462  0.436046  0.563667  0.587516
2021-03-21  0.947713  0.282269  0.136010  0.002212

In [47]:
type(df)

pandas.core.frame.DataFrame

In [50]:
# DataFrame이 보유한 values값들만 반환
df.values

array([[0.50705584, 0.7924678 , 0.86856009, 0.83307601],
       [0.20224871, 0.22428682, 0.51341143, 0.88245941],
       [0.14180031, 0.00961104, 0.41679496, 0.25226813],
       [0.48115725, 0.8371084 , 0.2170905 , 0.16800447],
       [0.99305906, 0.69700601, 0.34245427, 0.49658121],
       [0.39812129, 0.79181168, 0.11048354, 0.15003183],
       [0.05460461, 0.40585677, 0.81422896, 0.79019347],
       [0.00882385, 0.98098908, 0.56691345, 0.07110659],
       [0.34507701, 0.07441486, 0.60967037, 0.22928078],
       [0.58538329, 0.79818046, 0.24776932, 0.23669766],
       [0.17246202, 0.4360463 , 0.56366665, 0.58751578],
       [0.94771288, 0.2822689 , 0.13600986, 0.00221245]])

In [51]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 12 entries, 2021-03-10 to 2021-03-21
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       12 non-null     float64
 1   b       12 non-null     float64
 2   c       12 non-null     float64
 3   d       12 non-null     float64
dtypes: float64(4)
memory usage: 480.0 bytes


In [176]:
temp = [[np.random.randint(12) for i in range(4)] for i in range(12)]
print(temp)
df = pd.DataFrame(np.random.randint(12, size=(12, 4)), index=datas, columns=['a', 'b', 'c', 'd'])
df

[[5, 3, 5, 0], [10, 10, 6, 10], [4, 1, 5, 8], [2, 9, 10, 0], [8, 10, 11, 8], [6, 1, 0, 8], [3, 10, 9, 11], [3, 8, 7, 3], [8, 1, 11, 1], [5, 5, 2, 3], [0, 3, 0, 6], [10, 10, 8, 7]]


a   b  c   d
2021-03-10   1  11  7   0
2021-03-11   2  11  4   8
2021-03-12   4   9  9  10
2021-03-13   2   5  2   1
2021-03-14   9   2  5   2
2021-03-15  10   4  0   3
2021-03-16   0   0  9   7
2021-03-17   2   2  0   6
2021-03-18   1   8  8   1
2021-03-19   6   9  0  11
2021-03-20  10   5  3   9
2021-03-21   7   1  7   8

In [179]:
v = np.random.randint(12, size=(12, 4))
print(v.ndim)
print(v.shape)

2
(12, 4)


In [238]:
s1 = pd.Series([np.random.randint(1, 20) for i in range(20)])
df = pd.concat([s1], axis=1)
print(df)
df.info()

     0
0    5
1    4
2    3
3   11
4    2
5   19
6    4
7    5
8   15
9    7
10   8
11   4
12   2
13   9
14   5
15  13
16  16
17   2
18  12
19   4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20 non-null     int64
dtypes: int64(1)
memory usage: 288.0 bytes


In [249]:
df = pd.DataFrame(np.random.randint(12, size=(12, 4)), index=datas, columns=['a', 'b', 'c', 'd'])
df.describe()

a          b          c          d
count  12.000000  12.000000  12.000000  12.000000
mean    6.000000   6.166667   6.583333   5.500000
std     3.837613   3.996210   3.848455   3.554766
min     0.000000   1.000000   0.000000   0.000000
25%     4.000000   1.000000   4.750000   2.750000
50%     6.000000   7.500000   6.500000   6.000000
75%     9.000000   9.250000  10.250000   8.000000
max    11.000000  11.000000  11.000000  11.000000

In [250]:
df = pd.concat([s1], axis=1) # 0이면 series 1이면 DataFrame
# df.sort_values(by='b', ascending=True)
print(df)
type(df)

     0
0    5
1    4
2    3
3   11
4    2
5   19
6    4
7    5
8   15
9    7
10   8
11   4
12   2
13   9
14   5
15  13
16  16
17   2
18  12
19   4


pandas.core.frame.DataFrame

In [253]:
df = pd.DataFrame(np.random.randint(12, size=(12, 4)), index=datas, columns=['a', 'b', 'c', 'd'])
df.sort_value(by='b', ascending=True)

AttributeError: 'DataFrame' object has no attribute 'sort_value'

LOC 속성
1. 데이터를 slicing 하는 기술
2. loc[index, columns]

In [258]:
df = pd.DataFrame(np.random.randint(12, size=(12, 4)), index=datas, columns=['a', 'b', 'c', 'd'])
df.loc[:]

a   b   c   d
2021-03-10   7  11   4   6
2021-03-11  10   5   6   7
2021-03-12   8  11   3  10
2021-03-13   1   5  10   2
2021-03-14   0   2   7   9
2021-03-15   3   5   2   0
2021-03-16   5   0   7   2
2021-03-17   7   3   9   0
2021-03-18   7   3  11   9
2021-03-19  10   1   6   4
2021-03-20   2   1   2   5
2021-03-21   5   8   1   6

In [261]:
df.loc[['2021-03-10', '2021-03-11']]

a   b  c  d
2021-03-10   7  11  4  6
2021-03-11  10   5  6  7

In [287]:
df.iloc[[0, 2], [0, 2]]

a    c
2021-03-10  100  100
2021-03-12    8    3

In [305]:
df

a   b    c   d
2021-03-10  10  11  100   6
2021-03-11  10   5    6   7
2021-03-12   8  11    3  10
2021-03-13   1   5   10   2
2021-03-14   0   2    7   9
2021-03-15   3   5    2   0
2021-03-16   5   0    7   2
2021-03-17   7   3    9   0
2021-03-18   7   3   11   9
2021-03-19  10   1    6   4
2021-03-20   2   1    2   5
2021-03-21   5   8    1   6

In [293]:
df1 = df.copy()
df1

a   b    c   d
2021-03-10  10  11  100   6
2021-03-11  10   5    6   7
2021-03-12   8  11    3  10
2021-03-13   1   5   10   2
2021-03-14   0   2    7   9
2021-03-15   3   5    2   0
2021-03-16   5   0    7   2
2021-03-17   7   3    9   0
2021-03-18   7   3   11   9
2021-03-19  10   1    6   4
2021-03-20   2   1    2   5
2021-03-21   5   8    1   6

In [306]:
df1.iloc[0, [0]] = 100
df1

a   b    c   d
2021-03-10  100  11  100   6
2021-03-11   10   5    6   7
2021-03-12    8  11    3  10
2021-03-13    1   5   10   2
2021-03-14    0   2    7   9
2021-03-15    3   5    2   0
2021-03-16    5   0    7   2
2021-03-17    7   3    9   0
2021-03-18    7   3   11   9
2021-03-19   10   1    6   4
2021-03-20    2   1    2   5
2021-03-21    5   8    1   6

In [310]:
df = pd.DataFrame(np.random.randn(6, 4), columns=['A', 'B', 'C', 'D'])
df

A         B         C         D
0  0.561802  0.442468 -0.529470 -0.836520
1  0.609249  0.378906 -1.045778  1.149667
2 -0.208418 -1.089776 -0.657524 -0.453083
3  0.021954 -0.476814 -0.969282  0.188535
4 -0.741296  3.804880 -1.047776 -0.110058
5  0.589831  1.162115 -2.144416  2.438534

In [331]:
# 새로운 컬럼 추가 및 혹여 이미 존재하는 series였을 경우 데이터 갱신
df['E'] = [11, 2, 3, np.nan, 5, 6]
df

0                       11
1                        2
2                        3
3                        4
4                        5
5                        6
E    [11, 2, 3, nan, 5, 6]
Name: E, dtype: object

In [329]:
del(df['E'])

In [332]:
df['E'].isin([1, 2])

AttributeError: 'list' object has no attribute 'isin'

In [327]:
df = df['E'].fillna('4')
df

0    11
1     2
2     3
3     4
4     5
5     6
Name: E, dtype: int64

In [333]:
df = pd.DataFrame(np.random.randn(6, 4), columns=['A', 'B', 'C', 'D'])

In [335]:
# np.nan이 값으로 적용된 시리즈가 데이터프레임에 적용된 
df['E'] = [11, 2, 3, np.nan, 5, 6]
df

A         B         C         D     E
0  0.795432 -1.167900 -0.261312 -0.091526  11.0
1  1.092839 -0.636022 -1.639067 -0.213936   2.0
2 -1.474138  1.372294 -1.131835  1.022751   3.0
3  0.593839  0.736138  0.629235  1.685705   NaN
4  0.987705 -0.587197 -0.612011  0.033072   5.0
5 -0.686652  0.888263 -2.191811 -1.114380   6.0

In [371]:
df = pd.DataFrame({'float': [1.0],
                   'int': [1],
                   'datetime': [pd.Timestamp('20180310')],
                   'string': ['foo']})
df.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [372]:
d = {'col1' : [1, 2], 'col2' : [3, 4]}
df = pd.DataFrame(data=d)
print(df.dtypes)
print(df)

col1    int64
col2    int64
dtype: object
   col1  col2
0     1     3
1     2     4


In [373]:
df.astype('int32').dtypes
df.dtypes

col1    int64
col2    int64
dtype: object

결측치가 포함된 데이터 series타입은 숫자가 아닌 타입으로 적용했는지?

해결책 1 - 결측치 값 대체

    0으로? 평균? 중앙값? 빈도수가 높은 데이터?
    
해결책 2 - 타입 변경

    변경 가능한 타입으로 변경

In [374]:
df = df.astype('float64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    2 non-null      float64
 1   col2    2 non-null      float64
dtypes: float64(2)
memory usage: 160.0 bytes


np.nan값이 적용 될 경우 object타입 따라서 연산 불가

**외부 파일로 DataFrame 생성 및 관리**

In [388]:
df = pd.read_csv("../00.dataSet/friends.csv")
df

이름  나이   직업  hobby
0  신동엽  20  연예인  music
1  유재석  41   교수    art
2  김새롬  18   학생  study
3  이영자  45  상담사   talk
4  강호동  38  연예인   talk

In [391]:
df['이름']

0    신동엽
1    유재석
2    김새롬
3    이영자
4    강호동
Name: 이름, dtype: object

In [401]:
df.loc[3, '이름'] = '정찬우'
df

이름  나이   직업  hobby
0  신동엽  20  연예인  music
1  유재석  41   교수    art
2  김새롬  18   학생  study
3  정찬우  45  상담사   talk
4  강호동  38  연예인   talk

In [404]:
df = pd.read_csv("../00.dataSet/friendsTab.txt", delimiter="\t")
df

이름  나이   직업  hobby
0  신동엽  20  연예인  music
1  유재석  41   교수    art
2  김새롬  18   학생  study
3  이영자  45  상담사   talk
4  강호동  38  연예인   talk

In [461]:
df = pd.read_csv("../00.dataSet/friendsTabNoHead.txt", delimiter="\t", header=None)
type(df)
df.columns = ['name', 'age', 'job', 'hobby']
df

name  age  job  hobby
0  신동엽   20  연예인  music
1  유재석   41   교수    art
2  김새롬   18   학생  study
3  이영자   45  상담사   talk
4  강호동   38  연예인   talk

In [462]:
df = pd.read_csv("../00.dataSet/friendsTabNoHead.txt", delimiter="\t", header=None)
type(df)
df.columns = ['name', 'age', 'job', 'hobby']
df

name  age  job  hobby
0  신동엽   20  연예인  music
1  유재석   41   교수    art
2  김새롬   18   학생  study
3  이영자   45  상담사   talk
4  강호동   38  연예인   talk

In [464]:
df['salary'] = 0
df

name  age  job  hobby  salary
0  신동엽   20  연예인  music       0
1  유재석   41   교수    art       0
2  김새롬   18   학생  study       0
3  이영자   45  상담사   talk       0
4  강호동   38  연예인   talk       0

In [466]:
a = np.arange(10)
print(a)
np.where(a < 5, a, 10*a)

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [468]:
df['job']

0    연예인
1     교수
2     학생
3    상담사
4    연예인
Name: job, dtype: object

In [470]:
print(df['job'] != '학생')

0     True
1     True
2    False
3     True
4     True
Name: job, dtype: bool


In [473]:
df['salary'] = np.where(df['job'] != '학생', 'yes', 'no')
df

name  age  job  hobby salary
0  신동엽   20  연예인  music    yes
1  유재석   41   교수    art    yes
2  김새롬   18   학생  study     no
3  이영자   45  상담사   talk    yes
4  강호동   38  연예인   talk    yes